### PR TITLE
Scan for Networks While in AP Mode at an Interval

### PR DESCRIPTION
**Pull request by mattludwigs**
This should solve the issue of getting a stale list (or stuck with no
list) of access points to connect to.

### CODE REVIEW

**Comment by mattludwigs** [comment]
I guess I was trying to prevent scanning when we are not in AP mode

**Comment by mattludwigs** [comment]
I guess I was trying to prevent scanning when not in AP mode. I don't think it will hurt anything to try, but I just felt a little bad doing that, but I am all for less state management.

**Comment by jjcarstens** [comment]
Will VintageNet break if it attempts scan while not in AP mode? I think if we couple it with `run_wizard/0` or `start_server/0`, then it would only be scanning while the wizard is actively being used. But if it breaks things to scan when not in AP, then it has potential to ruin stuff while trying to apply a config to test connection

**Comment by mattludwigs** [comment]
With this model when we stop the wizard we will need to stop scanning, just so we are not constantly trying to scan forever.

**Comment by fhunleth** [comment]
Scanning when not in AP mode should work. I'm more used to using that than in AP mode. If the device is heavily transferring data on the network, then scans seem to cause hiccups, but that's not a problem here. The "fail busy" error should be transient.

**Pull request merged**
