### PR TITLE
Add button AP mode switching example

### PR DESCRIPTION
**Pull request by mattludwigs**

### CODE REVIEW

**Comment by fhunleth** [comment]
Looks good. For SmartRent, we need the HTTP port to be closed when not in AP mode. That could be a follow up PR if you want.

**Comment by mattludwigs** [comment]
Do you think that making the web endpoint stuff under a dynamic supervisor would make sense for this?

That will help with stopping and starting the web stuff, as well as solving a current race condition between checking if the WiFi is configured or not.

**Comment by fhunleth** [comment]
Yes

**Comment by mattludwigs** [comment]
I can make a follow-up PR for that then.

**Pull request merged**
